### ISSUE TITLE
got "Internal server error" for https://dandiarchive.org/dandiset/000004/draft

### ISSUE THREAD

**Issue by yarikoptic** [dandi/redirector#10]
Followed a link from https://github.com/dandi/dandi-cli/issues/68

```shell
$> curl https://dandiarchive.org/dandiset/000004/draft

    <h1>Internal Server Error</h1>
    <p>
        The server encountered an internal error and cannot complete
        your request.
    </p>
```

**Comment by satra** [comment]
@mgrauer - the girder endpoint api has changed behavior. we should in the future also adjust the redirector when the endpoint changes:

https://girder.dandiarchive.org/api/v1/dandi?identifier=000004

it looks like the above is now returning a list.

**Comment by mgrauer** [comment]
Sorry and thanks for the fix. It would be good if we can start nailing down our API surface of the server to the clients in the near-to-medium term.

**Comment by satra** [comment]
@mgrauer - one easy to test to add to the gui.dandiarchive.org client is to GET the permalink to see if it comes back to itself.

yes we should ensure that our internal client (dandi cli and redirector at the moment) needs for girder API are well documented.
