### ISSUE TITLE
Add to tests testing subset of dandi CLI

### ISSUE THREAD

**Issue by yarikoptic** [dandi/redirector#29]
So there is no unexpected changes in end result behavior - CLI should first be fixed, released before any breaking change in redirector happens.

edit: so tests should be done (also?) against pypi released version of dandi-cli

**Comment by yarikoptic** [comment]
FWIW, we have similar setup for datalad where we test development against released versions of extensions, and then test all extensions on cron job against released version of datalad to keep all components in working order

**Comment by jwodder** [comment]
What exactly are you asking for here?  Adding tests to redirector that run dandi-cli to see if it's compatible?  Exactly what parts of dandi-cli should the tests reach into?

**Comment by yarikoptic** [comment]
> Adding tests to redirector that run dandi-cli to see if it's compatible?

Yes

> Exactly what parts of dandi-cli should the tests reach into?

For starters - those which fail ATM. + Any other test which uses dandiarchive.org url or hits use of the instance.redirector . We could start with just those few, and then expand whenever we start to see more points of direct communication
