### ISSUE TITLE
Let's tag the beast?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/redirector#32]
now we even have tagged releases so there are tagged versions on hub.docker.com for them.  I think 0.1.0 of redirector would match them really nicely ATM ;)

(well, at some point I should get some datalad dataset with all of them, since what I was mumbling about in the past is coming: https://www.techradar.com/news/docker-could-be-set-to-delete-all-your-files-if-you-havent-accessed-them-for-a-while)

**Comment by yarikoptic** [comment]
tag me! tag me! ;)

**Comment by satra** [comment]
done.
