### ISSUE TITLE
Enable more of dandi-cli tests to possible talk to the "devel" instance redirector

### ISSUE THREAD

**Issue by yarikoptic** [dandi/redirector#35]
Build atop #33 (~~yet to be~~ merged)

- make `dandi-cli` talk to the localhost instance of redirector whenever it tries to reach out to `dandiarchive.org`:
  - I think it should be feasible to adjust compose script to host redirector on port 80, adjust `/etc/hosts` to point `dandiarchive.org` to the localhost
- run all dandi-cli tests, not just picked one/few.

**Comment by jwodder** [comment]
The dandi-cli tests access dandiarchive.org over HTTPS, so any attempt to mess with DNS would fail due to certificate errors.

**Comment by yarikoptic** [comment]
hm... indeed -- no go. ok, then I guess we are doomed to introduce/use a DANDI_REDIRECTOR_URL (env, and external defaulting to https://dandiarchive.org) variable which we just overload with `http://lcalhost:PORT` url?

**Comment by yarikoptic** [comment]
or may be it wouldn't be that "easy" idea since URLs we use try to get access to specific datasets on the main archive for which we do not provision in our test environment ATM, e.g. `https://dandiarchive.org/dandiset/000027/0.200721.2222` :-/

**Comment by jwodder** [comment]
@yarikoptic Can this be closed now that the old redirector is no more?

**Comment by yarikoptic** [comment]
yeah, let's just let it RiP
